export enum City {
  MADRID_SPAIN = 'MADRID_SPAIN',
  BARCELONA_SPAIN = 'BARCELONA_SPAIN',
  LONDRES_UK = 'LONDRES_UK',
  LASVEGAS_EEUU = 'LASVEGAS_EEUU',
  LOSANGELES_EEUU = 'LOSANGELES_EEUU',
  NUEVAYORK_EEUU = 'NUEVAYORK_EEUU',
}
